global:
  scrape_interval: 5s # Check my app every 5 seconds

scrape_configs:
  - job_name: 'spring-log-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
      # 'host.docker.internal' lets the container talk back to your laptop